import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} 
        antialiased m-0 p-0`}
      >
        {children}
        {/* Botão flutuante WhatsApp */}
        <a
          href="https://wa.me/5511991278863?text=Olá%20gostaria%20de%20um%20orçamento" // Substitua pelo número desejado
          target="_blank"
          rel="noopener noreferrer"
          className="fixed bottom-6 right-6 z-50 shadow-lg rounded-full"
          style={{ width: 64, height: 64 }}
        >
          <img
            src="/whatsapp.png"
            alt="WhatsApp"
            width={64}
            height={64}
            style={{ borderRadius: '50%' }}
            className="scale-100 hover:scale-110 transition-transform duration-200"
          />
        </a>
        {/* Fim do botão flutuante WhatsApp */}
      </body>
    </html>
  );
}
